version: '3.8'

services:
  # 開発用 Next.js アプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/fitconnect_dev
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
      - NEXT_PUBLIC_DEBUG_MODE=true
    depends_on:
      - db
      - redis
    networks:
      - fitconnect-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: npm run dev

  # PostgreSQL データベース (開発用)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fitconnect_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - fitconnect-dev-network
    restart: unless-stopped

  # Redis (開発用)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    networks:
      - fitconnect-dev-network
    restart: unless-stopped

  # pgAdmin (データベース管理ツール)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fitconnect.app
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - fitconnect-dev-network
    restart: unless-stopped

  # Redis Commander (Redis管理ツール)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - fitconnect-dev-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  fitconnect-dev-network:
    driver: bridge
